# Generated by Django 4.2.20 on 2025-04-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
