# Generated by Django 4.2.20 on 2025-04-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0006_remove_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
